-- Migration: Extend news table for automated collection
-- This adds fields to support AI-generated news articles

-- Add new columns to news table
ALTER TABLE news ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE news ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE news ADD COLUMN IF NOT EXISTS source_type VARCHAR(50) DEFAULT 'manual';
ALTER TABLE news ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE;
ALTER TABLE news ADD COLUMN IF NOT EXISTS tool_id UUID REFERENCES tools(id) ON DELETE SET NULL;
ALTER TABLE news ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE news ADD COLUMN IF NOT EXISTS engagement_score INTEGER DEFAULT 0;
ALTER TABLE news ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_news_category ON news(category);
CREATE INDEX IF NOT EXISTS idx_news_tool_id ON news(tool_id);
CREATE INDEX IF NOT EXISTS idx_news_published_on ON news(published_on DESC);
CREATE INDEX IF NOT EXISTS idx_news_ai_generated ON news(ai_generated);

-- Add comment
COMMENT ON COLUMN news.source_type IS 'manual, twitter, rss, scrape';
COMMENT ON COLUMN news.ai_generated IS 'Whether the article was generated by AI';
COMMENT ON COLUMN news.engagement_score IS 'Calculated from likes, shares, views';
